version: '2'

services:
  mongo:
    image: mongo
    container_name: mongo
  
  gist-cache-api:
    container_name: gist-cache-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080/tcp
